# Generated by Django 3.2 on 2022-02-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_auto_20220114_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='instagram',
            field=models.URLField(default=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram',
            field=models.URLField(default=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.URLField(default=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.URLField(default=None),
        ),
    ]
