# Generated by Django 3.2 on 2022-02-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_auto_20220202_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='instagram',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telegram',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='website',
            field=models.URLField(),
        ),
    ]
