# Generated by Django 3.2 on 2022-02-03 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0004_auto_20220202_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='telegram',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='website',
        ),
    ]
