# Generated by Django 3.2 on 2022-02-01 11:12

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_auto_20220201_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='created',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
    ]
