# Generated by Django 3.2 on 2022-02-01 11:13

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_alter_like_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_and_time',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
    ]
